version: "2"
services:
  app:
    container_name: ms-transactions-app
    restart: always
    build: .
    ports:
      - "8080:3000"
    links:
      - mongo
  mongo:
    container_name: ms-transactions-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
